# Generated by Django 4.1.1 on 2022-10-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
