# Generated by Django 4.1.1 on 2022-09-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0004_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='input address', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('ordered', 'Ordered'), ('success', 'Success'), ('fail', 'Fail')], default='cart', help_text='Order status', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books111', to='books.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders111', to='orders.order'),
        ),
    ]
