# Generated by Django 4.1.1 on 2022-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_address_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('ordered', 'Ordered'), ('success', 'Success'), ('fail', 'Fail')], default='cart', help_text='choices order status: Cart or Ordered', max_length=10),
        ),
    ]
