# Generated by Django 4.1.1 on 2022-09-18 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(blank=True, choices=[('i', 'In_work'), ('s', 'Success'), ('f', 'Fail')], default='i', help_text='Order status', max_length=1)),
                ('delivery_address', models.CharField(help_text='delivery address', max_length=255)),
                ('order_id_in_shop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('book_store_id', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this particular book in the warehouse and shop', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('book_item_id', models.ManyToManyField(to='books.bookitem')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
